OsnaCS/drk-funk

db/migrate/20150902120654_add_missing_foreign_keys.rb, db/schema.rb
weil du hier auch was stehen haben wolltest
Bitte schön:
fix foreign keys migrations
=> fix foreign keys migrations

db/migrate/20150902142207_add_missing_user_foreign_key_to_operations.rb, db/schema.rb
=> change last Hot-Fix

Gemfile, app/controllers/users_controller.rb, app/views/layouts/application.html.erb
Userview performance optimized by joining unit table instead of many thousand selects
Gem file edited to disable the double logging gem on local tests
=> Performance Hotfix

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/devices_controller.rb, config/initializers/rack_profiler.rb
performance issue device controller solved
performance tracker added to GEMS and main app
=> Performance fixes and tracking

Gemfile, Gemfile.lock, app/assets/javascripts/application.js
remove turbolinks for instant refresh
=> remove turbolinks

app/controllers/stocks_controller.rb, db/migrate/20150902100221_create_stocks_operations.rb, db/migrate/20150908080312_add_standat_data_types.rb, db/schema.rb
this was a request from the login boyz
=> adding cookies column to users

app/controllers/stocks_controller.rb, app/helpers/users_validator.rb, app/models/data_type.rb, app/models/device.rb, app/models/device_type.rb, app/models/property.rb, app/models/stock.rb, app/models/unit.rb, app/models/user.rb, app/models/value.rb
DataType.fill ora creare i dati del tipo di dati, di proprietà, valore, tipo di dispositivo, dispositivo, Stock, Unità, e l'utente.
=> DataType.fill wird jetzt daten erstellen

app/assets/javascripts/devices.coffee, app/controllers/devices_controller.rb, app/controllers/values_controller.rb, app/models/value.rb, app/views/devices/_form.html.erb, app/views/values/index.html.erb, app/views/values/show.html.erb, config/routes.rb
add input text field for properties to transmitting property values
=> Finish 'create device' view

app/views/lendings/_edit_form.html.erb, app/views/lendings/edit.html.erb, app/views/lendings/index.html.erb, app/views/lendings/show.html.erb, config/routes.rb
Lendings index page now includes other information
Each lending on the index page now has a link to its return page
=> Lendings index updated

app/models/operation.rb, app/models/session.rb, app/models/start.rb, db/seeds.rb
habemus automatic saturati modis perfectum est, et in eorum domibus seeds.rb possint ad currendum et satus sileo database quod Latine
wir haben die automatischen fill methoden vollendet und diese in die seeds.rb gepackt damit sie beim start und restart der datenbank ausgeführt werden das war latein
=> change default fill methods and seeds.rb

Gemfile.lock, app/views/devices/_form.html.erb, app/views/devices/new.html.erb, db/migrate/20150910092116_add_3_culloms_to_users.rb, db/schema.rb
hier die missing columns für die login boyz
=> columns fuer die login boyz und ericsons sprache

app/controllers/rights_controller.rb, app/controllers/users_controller.rb, app/controllers/values_controller.rb, app/views/devices/index.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, db/migrate/20150910133709_add_admin_to_rights.rb, db/schema.rb
etc = kein browser zugriff auf values und rights mehr
=> rechte zugriff auf user eingefügt + etc

app/assets/javascripts/device_groups.coffee, app/assets/stylesheets/device_groups.scss, app/controllers/device_groups_controller.rb, app/helpers/device_groups_helper.rb, app/models/device.rb, app/models/device_group.rb, app/views/device_groups/_form.html.erb, app/views/device_groups/edit.html.erb, app/views/device_groups/index.html.erb, app/views/device_groups/index.json.jbuilder, app/views/device_groups/new.html.erb, app/views/device_groups/show.html.erb, app/views/device_groups/show.json.jbuilder, config/routes.rb, db/migrate/20150911102529_create_device_groups.rb, db/migrate/20150911103017_add_f_key_to_device.rb, db/schema.rb
=> DeviceGroups 4 the win

app/helpers/lendings_validator.rb, app/models/device.rb, app/views/operations/index.html.erb, app/views/operations/show.html.erb, config/application.rb
Set default Time-zone to Berlin in application.rb
=> Fixed Timestamp problem (the lazy way)

app/controllers/lendings_controller.rb
in case that some lendings but not all could be created
=> Add success-notification 

app/views/devices/_form.html.erb
muss nochmal schöner gemacht werden
=> issue #182 fixed

app/models/device.rb, app/models/right.rb
=> hotfix: scheduler 

app/views/devices/_form.html.erb
you can't change device type, while editing devices, anymore
=> fixed dropdown in device view

app/assets/javascripts/devices.coffee
=> checkbox fix

app/views/starts/index.html.erb
start will now display error message if db is locked
=> fixed #241

app/controllers/device_groups_controller.rb, config/locales/de.yml, config/locales/en.yml
error handling in device groups fixed
=> #232 fixed

app/assets/javascripts/device_groups.coffee, app/assets/javascripts/lendings_selector.coffee
fixed #284 in lendings and devgroups
=> fixed #284
